/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import DomainModels.ChiTietSach;
import DomainModels.KhuyenMai;
import DomainModels.KhuyenMaiSach;
import Repository.KhuyenMaiRepository;
import Repository.QLSachRepository;
import Service.Implement.KhuyenMaiSachImpl;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author This PC
 */
public class FormKhuyenMaiSach extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    private KhuyenMaiSachImpl service;
    private QLSachRepository serviceS;
    private KhuyenMaiRepository serviceKM;
    private String isClicked;
    private String idKM;

    /**
     * Creates new form FormKhuyenMaiSach
     */
    public FormKhuyenMaiSach() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        rdoHetHan.setSelected(true);
        service = new KhuyenMaiSachImpl();
        serviceS = new QLSachRepository();
        serviceKM = new KhuyenMaiRepository();
        loadTable();
        for (ChiTietSach item : serviceS.getAll()) {
            cboSach.addItem(item.getMa());
        }
        for (KhuyenMai item : serviceKM.getAll()) {
            cboKM.addItem(item.getMa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cboSach = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboKM = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        txtSTCL = new javax.swing.JTextField();
        rdoHetHan = new javax.swing.JRadioButton();
        rdoConHan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtTK = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKMHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1010, 640));

        jLabel2.setText("Ma Sach:");

        jLabel3.setText("Ma Khuyen Mai:");

        jLabel4.setText("Don Gia:");

        jLabel5.setText("So Tien Con Lai:");

        txtDonGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDonGiaMouseExited(evt);
            }
        });

        buttonGroup1.add(rdoHetHan);
        rdoHetHan.setText("Het Han");

        buttonGroup1.add(rdoConHan);
        rdoConHan.setSelected(true);
        rdoConHan.setText("Con Han");

        jLabel7.setText("Trang Thai:");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtTK.setText("Tim Kiemmm...");
        txtTK.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTKCaretUpdate(evt);
            }
        });
        txtTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTKMouseExited(evt);
            }
        });

        tblKMHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ma Sach", "Ma Khuyen Mai", "Don Gia", "So Tien Con Lai", "Trang Thai"
            }
        ));
        tblKMHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKMHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKMHD);

        jPanel3.setBackground(new java.awt.Color(116, 119, 189));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Khuyến mãi sách");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(813, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(btnThem)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoConHan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoHetHan)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnXoa))
                            .addComponent(txtSTCL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSach, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboKM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSTCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoConHan)
                            .addComponent(rdoHetHan)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public boolean valid() {
        if (txtDonGia.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Don gia khong duoc trong!");
            return false;
        }
        return true;
    }

    public void loadTable() {
        model = (DefaultTableModel) tblKMHD.getModel();
        model.setRowCount(0);
        for (KhuyenMaiSach item : service.getList()) {
            model.addRow(new Object[]{
                item.getId(), service.getMaSachByID(item.getIdSach()), service.getMaKMByID(item.getIdKM()), item.getDonGia(), item.getSoTienConLai(), service.getTrangThai(item.getTinhTrang())
            });
        }
    }

    public void loadTableTK() {
        model = (DefaultTableModel) tblKMHD.getModel();
        model.setRowCount(0);
        for (KhuyenMaiSach item : service.searchKM(txtTK.getText())) {
            model.addRow(new Object[]{
                item.getId(), service.getMaSachByID(item.getIdSach()), service.getMaKMByID(item.getIdKM()), item.getDonGia(), item.getSoTienConLai(), service.getTrangThai(item.getTinhTrang())
            });
        }
    }

    public KhuyenMaiSach getAllFromGUI() {
        int tt;
        if (rdoHetHan.isSelected()) {
            tt = 0;
        } else {
            tt = 1;
        }
        return new KhuyenMaiSach(null, service.getIdSachByMa(cboSach.getSelectedItem().toString()), service.getIdKhuyenMaiByMa(cboKM.getSelectedItem().toString()), Float.parseFloat(txtDonGia.getText()), Float.parseFloat(txtSTCL.getText()), tt);
    }

    private void txtDonGiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDonGiaMouseExited
        // TODO add your handling code here:
        txtSTCL.setText((Float.parseFloat(txtDonGia.getText()) * (100 - Float.parseFloat(service.getPhanTramByIdKM(idKM))) / 100) + "");
    }//GEN-LAST:event_txtDonGiaMouseExited

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Xac Nhan");
        if (confirm == 0) {
            if (valid()) {
                JOptionPane.showMessageDialog(this, service.them(getAllFromGUI()));
                loadTable();
            }
        } else if (confirm == 1) {
            JOptionPane.showMessageDialog(this, "Da Huy");
        } else {
            JOptionPane.showMessageDialog(this, "Da Huy");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        var temp = getAllFromGUI();
        temp.setId(isClicked);
        int confirm = JOptionPane.showConfirmDialog(this, "Xac Nhan");
        if (confirm == 0) {
            JOptionPane.showMessageDialog(this, service.sua(temp));
            loadTable();
        } else if (confirm == 1) {
            JOptionPane.showMessageDialog(this, "Da Huy");
        } else {
            JOptionPane.showMessageDialog(this, "Da Huy");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        KhuyenMaiSach temp = new KhuyenMaiSach();
        temp.setId(isClicked);
        int confirm = JOptionPane.showConfirmDialog(this, "Xac Nhan");
        if (confirm == 0) {
            JOptionPane.showMessageDialog(this, service.xoa(temp));
            loadTable();
        } else if (confirm == 1) {
            JOptionPane.showMessageDialog(this, "Da Huy");
        } else {
            JOptionPane.showMessageDialog(this, "Da Huy");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTKCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTKCaretUpdate
        // TODO add your handling code here:
        loadTableTK();
    }//GEN-LAST:event_txtTKCaretUpdate

    private void txtTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTKMouseExited
        // TODO add your handling code here:
        txtTK.setText("Tim Kiemmmm ...");
        loadTable();
    }//GEN-LAST:event_txtTKMouseExited

    private void tblKMHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKMHDMouseClicked
        // TODO add your handling code here:
        int row = tblKMHD.getSelectedRow();
        if (row == -1) {
            return;
        }
        isClicked = tblKMHD.getModel().getValueAt(row, 0).toString();
        var temp = service.getKMSachByID(isClicked);
        cboSach.setSelectedItem(service.getMaSachByID(temp.getIdSach()));
        cboKM.setSelectedItem(service.getMaKMByID(temp.getIdKM()));
        txtDonGia.setText(temp.getDonGia().toString());
        txtSTCL.setText(temp.getSoTienConLai().toString());
        if (temp.getTinhTrang() == 0) {
            rdoHetHan.setSelected(true);
            txtSTCL.setText(temp.getDonGia().toString());
            KhuyenMaiSach kms = service.getKMSachByMaKMSach(service.getMaKMByID(temp.getIdKM()));
            kms.setSoTienConLai(temp.getDonGia());
        } else {
            rdoConHan.setSelected(true);
        }

        idKM = service.getIdKhuyenMaiByMa(tblKMHD.getModel().getValueAt(row, 2).toString());

    }//GEN-LAST:event_tblKMHDMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormKM km =new FormKM();
        km.setVisible(true);
        km.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboKM;
    private javax.swing.JComboBox<String> cboSach;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdoConHan;
    private javax.swing.JRadioButton rdoHetHan;
    private javax.swing.JTable tblKMHD;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSTCL;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
