/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Service.Implement.ThongKeServiceImpl;
import Service.ThongKeService;
import ViewModels.ChartThongKe;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author acer
 */
public class FormThongKe_DoanhThu extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormThongKe_DoanhThu
     */
    private ThongKeService service = new ThongKeServiceImpl();
    public FormThongKe_DoanhThu() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setDataChart(panelTK1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTK1 = new javax.swing.JPanel();
        panelTK2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1010, 640));

        javax.swing.GroupLayout panelTK1Layout = new javax.swing.GroupLayout(panelTK1);
        panelTK1.setLayout(panelTK1Layout);
        panelTK1Layout.setHorizontalGroup(
            panelTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        panelTK1Layout.setVerticalGroup(
            panelTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTK2Layout = new javax.swing.GroupLayout(panelTK2);
        panelTK2.setLayout(panelTK2Layout);
        panelTK2Layout.setHorizontalGroup(
            panelTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTK2Layout.setVerticalGroup(
            panelTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setDataChart(JPanel panel) {
        List<ChartThongKe> list = service.chartThongKe();
        if(list != null) {
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for (ChartThongKe item : list) {
                dataset.setValue(item.getDoanhThu(), "Doanh thu", item.getThang());
            }
            JFreeChart chart = ChartFactory.createBarChart("Thong ke doanh thu", "Thoi gian", "Doanh thu", dataset);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(panel.getWidth(), 300));
            
            panel.removeAll();
            panel.setLayout(new CardLayout());
            panel.add(chartPanel);
            panel.validate();
            panel.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelTK1;
    private javax.swing.JPanel panelTK2;
    // End of variables declaration//GEN-END:variables
}
