/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import DomainModels.NXB;
import DomainModels.Sach;
import DomainModels.TacGia;
import DomainModels.TheLoai;
import Service.Implement.NXBimpl;
import Service.Implement.SachServiceImpl;
import Service.Implement.TacGiaBimpl;
import Service.Implement.Theloaiimpl;
import Service.NXBService;
import Service.SachService;
import Service.TacGiaService;
import Service.TheLoaiService;
import ViewModels.QLSach;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class FormQLSach extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormQLSach
     */
    private SachService service = new SachServiceImpl();
    private NXBService nXBService = new NXBimpl();
    private TacGiaService tgService = new TacGiaBimpl();
    private TheLoaiService tlService = new Theloaiimpl();
    DefaultTableModel model;
    DefaultComboBoxModel modelCBNXB;
    DefaultComboBoxModel modelCBTG;
    DefaultComboBoxModel modelCBTL;

    public FormQLSach() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        loadTable();
        loadCBNXB();
        loadCBTG();
        loadCBTL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        rdConSach = new javax.swing.JRadioButton();
        rdHetSach = new javax.swing.JRadioButton();
        txtSoLuongTon = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboTheLoai = new javax.swing.JComboBox<>();
        cboNXB = new javax.swing.JComboBox<>();
        cboTacGia = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        themNXB = new javax.swing.JButton();
        themTL = new javax.swing.JButton();
        themTG = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1010, 640));

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ma", "Ten", "The loai", "NXB", "Tac gia", "Mo ta", "So luong ton", "Gia", "Tinh trang", "Anh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSach);
        if (tblSach.getColumnModel().getColumnCount() > 0) {
            tblSach.getColumnModel().getColumn(0).setResizable(false);
            tblSach.getColumnModel().getColumn(1).setResizable(false);
            tblSach.getColumnModel().getColumn(2).setResizable(false);
            tblSach.getColumnModel().getColumn(3).setResizable(false);
            tblSach.getColumnModel().getColumn(4).setResizable(false);
            tblSach.getColumnModel().getColumn(5).setResizable(false);
            tblSach.getColumnModel().getColumn(6).setResizable(false);
            tblSach.getColumnModel().getColumn(7).setResizable(false);
            tblSach.getColumnModel().getColumn(8).setResizable(false);
            tblSach.getColumnModel().getColumn(9).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUAN LY SACH");

        jLabel3.setText("Ten");

        jLabel4.setText("Mo ta");

        jLabel5.setText("So luong ton");

        jLabel6.setText("Gia");

        jLabel7.setText("Tinh trang");

        jLabel8.setText("Ma");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        buttonGroup1.add(rdConSach);
        rdConSach.setText("Con sach");
        rdConSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdConSachActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdHetSach);
        rdHetSach.setText("Het sách");

        jLabel2.setText("The loai");

        jLabel10.setText("NXB");

        jLabel13.setText("Tac gia");

        jLabel14.setText("Anh");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        themNXB.setText("+");
        themNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNXBActionPerformed(evt);
            }
        });

        themTL.setText("+");
        themTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTLActionPerformed(evt);
            }
        });

        themTG.setText("+");
        themTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMa)
                                        .addComponent(txtTen)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdConSach)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdHetSach))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuongTon)
                                    .addComponent(txtGia))))
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(cboNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnThem))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnTim)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(themNXB)
                            .addComponent(themTG)
                            .addComponent(themTL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {themNXB, themTG, themTL});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themTL)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cboNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cboTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(themTG))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(rdConSach)
                                    .addComponent(rdHetSach))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(themNXB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua)
                            .addComponent(btnThem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {themNXB, themTG, themTL});

        jLabel14.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdConSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdConSachActionPerformed

    }//GEN-LAST:event_rdConSachActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String ma = txtMa.getText();
        if (service.search(ma) != null) {
            JOptionPane.showMessageDialog(this, "Tim kiem thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "Tim kiem that bai");
            return;
        }
        model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);
        List<QLSach> list = service.search(ma);
        for (QLSach s : list) {
            model.addRow(new Object[]{s.getMa(), s.getTen(), s.getTheLoai(), s.getNXB(), s.getTacGia(), s.getMoTa(), s.getSoLuongTon(), s.getGia(), s.getTinhTrang(), s.getAnh()});
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String moTa = txtMoTa.getText();
        int tinhTrang;
        if (rdConSach.isSelected()) {
            tinhTrang = 1;
        } else {
            tinhTrang = 0;
        }
        int soLuongTon = Integer.parseInt(txtSoLuongTon.getText());
        Double gia = Double.parseDouble(txtGia.getText());

        TheLoai tl = (TheLoai) cboTheLoai.getSelectedItem();
        String idTL = tl.getId();

        TacGia tg = (TacGia) cboTacGia.getSelectedItem();
        String idTG = tg.getId();

        NXB nxb = (NXB) cboNXB.getSelectedItem();
        String idNXB = tl.getId();

        Sach s = new Sach(ma, ten, soLuongTon, moTa, tinhTrang, idTL, idNXB, idTG, gia, null);
        if (service.createSach(s) == 1) {
            JOptionPane.showMessageDialog(this, "Them sach thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "Them sach that bai");
            return;
        }
        loadTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String moTa = txtMoTa.getText();
        int tinhTrang;
        if (rdConSach.isSelected()) {
            tinhTrang = 1;
        } else {
            tinhTrang = 0;
        }
        int soLuongTon = Integer.parseInt(txtSoLuongTon.getText());
        Double gia = Double.parseDouble(txtGia.getText());

        TheLoai tl = (TheLoai) cboTheLoai.getSelectedItem();
        String idTL = tl.getId();

        TacGia tg = (TacGia) cboTacGia.getSelectedItem();
        String idTG = tg.getId();

        NXB nxb = (NXB) cboNXB.getSelectedItem();
        String idNXB = tl.getId();

        Sach s = new Sach(ma, ten, soLuongTon, moTa, tinhTrang, idTL, idNXB, idTG, gia, null);
        if (service.updateSach(s, ma) == 1) {
            JOptionPane.showMessageDialog(this, "Sua thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "Sua that bai");
            return;
        }
        loadTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void themTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTLActionPerformed
        FormTheLoai tl =new FormTheLoai();
        tl.setVisible(true);
        tl.setLocationRelativeTo(this);
    }//GEN-LAST:event_themTLActionPerformed

    private void themNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNXBActionPerformed
        FormNXB nxb =new FormNXB();
        nxb.setVisible(true);
        nxb.setLocationRelativeTo(this);
    }//GEN-LAST:event_themNXBActionPerformed

    private void themTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTGActionPerformed
        FormTacGia tg =new FormTacGia();
        tg.setVisible(true);
        tg.setLocationRelativeTo(this);
    }//GEN-LAST:event_themTGActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboNXB;
    private javax.swing.JComboBox<String> cboTacGia;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdConSach;
    private javax.swing.JRadioButton rdHetSach;
    private javax.swing.JTable tblSach;
    private javax.swing.JButton themNXB;
    private javax.swing.JButton themTG;
    private javax.swing.JButton themTL;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);
        List<QLSach> list = service.getAll();
        for (QLSach s : list) {
            model.addRow(new Object[]{s.getMa(), s.getTen(), s.getTheLoai(), s.getNXB(), s.getTacGia(), s.getMoTa(), s.getSoLuongTon(), s.getGia(), s.getTinhTrang(), s.getAnh()});
        }
    }

    private void loadCBNXB() {
        modelCBNXB = (DefaultComboBoxModel) cboNXB.getModel();
        List<NXB> list = nXBService.getAll();
        for (NXB nxb : list) {
            modelCBNXB.addElement(nxb.getTen());
        }
    }

    private void loadCBTG() {
        modelCBTG = (DefaultComboBoxModel) cboTacGia.getModel();
        List<TacGia> list = tgService.getAll();
        for (TacGia tg : list) {
            modelCBTG.addElement(tg.getTen());
        }

    }

    private void loadCBTL() {
        modelCBTL = (DefaultComboBoxModel) cboTheLoai.getModel();
        List<TheLoai> list = tlService.getAll();
        for (TheLoai tl : list) {
            modelCBTL.addElement(tl.getTen());
        }
    }
}
